default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: datagophers_dev

production:
  <<: *default
  database: datagophers_pro
  username: datagophers
  password: <%= ENV['DATAGOPHERS_DATABASE_PASSWORD'] %>
